apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-app.fullname" . }}
  labels:
    app: {{ include "test-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "test-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "test-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["bash"]
          args: ["-c", "sleep 1000"]
          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /opt/app/configs
      volumes:
        - name: config-volume
          configMap:
            name: test-configmap
