replicaCount: 1

image:
  repository: ubuntu
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80

resources: 
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "200Mi"