replicaCount: 1

image:
  repository: ubuntu
  tag: "latest"
  pullPolicy: IfNotPresent

args: ["sleep", "1000"]

service:
  type: ClusterIP
  port: 80

configMap:
  data:
    config1.conf: |
      # Example configuration file
      key1 = value1
      key2 = value2
    config2.conf: |
      # Another example configuration file
      setting1 = option1
      setting2 = option2

resources: 
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "200Mi"